/*
  Builds ../lockon.js — the vendored, fully-offline "Lock-On" model runtime
  (v4 epic, Phase 1): onnxruntime-web's WASM engine plus a YOLOX-Nano person
  detector, all in ONE file loadable via <script src> from file:// (fetch() of
  local files does not work there, script tags do).

  The generated file is COMMITTED. This script only exists so the artifact is
  reproducible and its provenance checkable: it downloads pinned versions,
  verifies their SHA-256, and emits the same lockon.js byte-for-byte.

    node make-lockon.js          # writes ../lockon.js

  What goes in, and why these:
  - onnxruntime-web 1.17.3 (MIT, (c) Microsoft) — ort.wasm.min.js + the
    wasm-simd binary. 1.17.3 specifically: its UMD bundle embeds the JS glue,
    so a blob-URL wasmPaths override is enough to boot with zero network.
    1.19.x's wasm backend dynamic-imports a separate .mjs whose URL resolution
    throws "Invalid URL" under file:// — measured, not assumed.
  - YOLOX-Nano (Apache-2.0, (c) Megvii) — 3.66MB ONNX, 416x416 input, COCO
    classes, raw output [1,3549,85] (grids at strides 8/16/32; decode+NMS live
    in index.html where they are testable). Chosen over YOLOv5/v8-class models
    for the licence (those are AGPL) at comparable nano-tier accuracy.

  Both payloads are gzipped then base64'd (19MB -> ~8.5MB on disk); the loader
  inflates with DecompressionStream, which every browser new enough to run the
  detector has anyway. Browsers without it reject load() and the app falls
  back to the v3.7 tracker — the model is a progressive enhancement, never a
  requirement.
*/
'use strict';
const fs = require('fs');
const path = require('path');
const os = require('os');
const crypto = require('crypto');
const { execSync } = require('child_process');
const zlib = require('zlib');

const ORT_VERSION = '1.17.3';
const YOLOX_URL = 'https://github.com/Megvii-BaseDetection/YOLOX/releases/download/0.1.1rc0/yolox_nano.onnx';
const SHA256 = {
  'ort.wasm.min.js':    '654435ead2d823e56d5893ec53be49f6ddb7e827096561aae63501071470cf23',
  'ort-wasm-simd.wasm': '6783fcd6647ce1b426a527c31412a9c40894552faa609e9c931b3239a3438071',
  'yolox_nano.onnx':    'c789161ed43c8269fcd4e67c67eeeb4e80c622da2eb296a20bc6007bd18a0b7d',
};

const OUT = path.resolve(__dirname, '..', 'lockon.js');

function sha256(buf){ return crypto.createHash('sha256').update(buf).digest('hex'); }
function verify(name, buf){
  const h = sha256(buf);
  if (h !== SHA256[name])
    throw new Error(`${name}: sha256 mismatch\n  expected ${SHA256[name]}\n  got      ${h}\nUpstream changed — inspect before trusting it, then update the pin.`);
  console.log(`  ${name}  ${(buf.length / 1e6).toFixed(2)}MB  sha256 OK`);
}

function main(){
  const work = fs.mkdtempSync(path.join(os.tmpdir(), 'lockon-'));
  console.log('fetching pinned artifacts...');
  execSync(`npm pack onnxruntime-web@${ORT_VERSION} --silent`, { cwd: work, stdio: 'pipe' });
  execSync(`tar xzf onnxruntime-web-${ORT_VERSION}.tgz`, { cwd: work });
  const ortJs = fs.readFileSync(path.join(work, 'package', 'dist', 'ort.wasm.min.js'));
  const wasm = fs.readFileSync(path.join(work, 'package', 'dist', 'ort-wasm-simd.wasm'));
  execSync(`curl -sSL -o yolox_nano.onnx "${YOLOX_URL}"`, { cwd: work });
  const model = fs.readFileSync(path.join(work, 'yolox_nano.onnx'));

  verify('ort.wasm.min.js', ortJs);
  verify('ort-wasm-simd.wasm', wasm);
  verify('yolox_nano.onnx', model);

  const gz = b => zlib.gzipSync(b, { level: 9 }).toString('base64');
  const out = [
    '/* Film Room "Lock-On" model runtime — GENERATED by tests/make-lockon.js. Do not edit.',
    '',
    '   Bundles, for fully-offline on-device player detection (footage never leaves',
    '   the machine; this file makes no network requests of any kind):',
    `   - onnxruntime-web ${ORT_VERSION} — MIT License, (c) Microsoft Corporation`,
    '     https://github.com/microsoft/onnxruntime',
    '   - YOLOX-Nano ONNX model — Apache License 2.0, (c) Megvii, Inc.',
    '     https://github.com/Megvii-BaseDetection/YOLOX',
    '   Payloads are gzip+base64; window.__lockon.load() inflates and boots them.',
    '   If this file is absent or the browser cannot run it, Film Room falls back',
    '   to its built-in tracker — this is an enhancement, never a requirement. */',
    ortJs.toString('utf8'),
    ';(function(){',
    '"use strict";',
    'function un64(s){var b=atob(s),a=new Uint8Array(b.length);for(var i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return a;}',
    'async function gunzip(u8){var r=new Response(new Blob([u8]).stream().pipeThrough(new DecompressionStream("gzip")));return new Uint8Array(await r.arrayBuffer());}',
    'var wasmGz=' + JSON.stringify(gz(wasm)) + ';',
    'var modelGz=' + JSON.stringify(gz(model)) + ';',
    'var ready=null;',
    'window.__lockon={',
    ' meta:{detector:"YOLOX-Nano",detectorLicence:"Apache-2.0",runtime:"onnxruntime-web ' + ORT_VERSION + '",runtimeLicence:"MIT",input:416,version:1},',
    ' ort:ort,',
    ' load:function(){',
    '  if(ready)return ready;',
    '  return ready=(async function(){',
    '   if(typeof DecompressionStream==="undefined")throw new Error("browser too old for the detector (no DecompressionStream)");',
    '   var wasm=await gunzip(un64(wasmGz));',
    '   var model=await gunzip(un64(modelGz));',
    '   wasmGz=modelGz=null;',
    '   var wasmUrl=URL.createObjectURL(new Blob([wasm],{type:"application/wasm"}));',
    '   ort.env.wasm.numThreads=1;',
    '   /* only the simd names: a browser without WASM-SIMD must fail here and fall',
    '      back to the built-in tracker, not be handed a binary it cannot run */',
    '   ort.env.wasm.wasmPaths={"ort-wasm-simd.wasm":wasmUrl,"ort-wasm-simd-threaded.wasm":wasmUrl};',
    '   return {ort:ort,model:model};',
    '  })();',
    ' }',
    '};',
    '})();',
    '',
  ].join('\n');
  fs.writeFileSync(OUT, out);
  console.log(`wrote ${OUT} (${(out.length / 1e6).toFixed(2)}MB)`);
  fs.rmSync(work, { recursive: true, force: true });
}

main();
